version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"  # Opcional: Mapea el puerto 3306 del contenedor al puerto 3306 del host

  backend:
    build:
      context: .  # Ruta al directorio del backend
    ports:
      - "8000:8000"  # Puerto del backend
    volumes:
      - ./backend:/app  # Montar el código del backend como volumen
    depends_on:
      - db  # Indica que el contenedor de backend depende del contenedor de base de datos

  frontend:
    build:
      context: ./client  # Ruta al directorio del cliente web
    ports:
      - "3000:3000"  # Puerto del cliente web
    volumes:
      - ./frontend:/app  # Montar el código del cliente web como volumen
    command: npm start  # Comando para ejecutar el cliente web
    depends_on:
      - backend

volumes:
  mysql_data: