# Generated by Django 5.0.3 on 2024-03-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.CharField(default=123, max_length=10, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='desc', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
